### ISSUE TITLE
About FBX resource import？

### ISSUE THREAD

**Issue by myluoxz** [ConfettiFX/The-Forge#100]
Consult the resource pipeline documentation

Known problems:
-Skeletons and animations scaled from centimeters to meters (* 0.01). This is only required for FBX files. If we want to support other formats this has to be changed.
-See: AssetPipeline.cpp - line: 392 & 537 & 546
-Boris (Unreal Paragon asset) rotated 90 degrees on x axis after putting it through the animation pipeline. Blender also doesn’t import model correctly. Rotating the model in either Maya or Blender causes severe problems in the animation. Makes it look like his nose, fingers and ankle are all broken.

The bone file generated by fbx2ozz is correct。
AssetPipelineCmd.exe generated skeletal  rotated 90 degrees on x axis ?

How should fbx be exported or how to set it correctly, I use

```
		AssimpImporter        importer;
		AssimpImporter::Model model = {};
		if (!importer.ImportModel(fullPath.c_str(), &model))
			return false;

```
The fbx model is magnified n times, The FBX in the example is correct, how should the FBX model be derived

**Comment by myluoxz** [comment]
I want to use the application provided by the fbx2ozz.exe ozz engine to generate bones and animations, use The-Forge Engine AssimpImporter code to import skins, do not need AssetPipelineCmd.exe, is it ok?

**Comment by timoconffx** [comment]
The version of Assimp we used while this unit test was written had an issue that caused all meshes to be 100x larger than intended and rotated on the x-axis. This is because in the FBX the mesh is stored in centimeters instead of meters and because most modelling tools use a different coordinate system. We added a workaround for this behaviour in the AssetPipeline. If the scale of your model is incorrect, try exporting it in meters using your favourite modeling tool. Our model is only a couple of units(meters) tall. Make sure yours is the about the same. 

We used to use animations and skeletons exported through fbx2ozz.exe internally for testing purposes. I can't think if any reason why they wouldn't work now.

**Comment by myluoxz** [comment]
Hi.

Thanks for the reply.

I used the example  simpleTest\riggedMesh.fbx, simpleTest\twistShift.fbx bones and animations to test, import the animation into max, and then export the FBX file, whether it is Y axis or Z axis up, the animation is always put down 90 degrees, but Maya import and then export That's right, I think it's a good resource to handle this piece of code.

I hope to improve the code of this piece.

**Comment by wolfgangfengel** [comment]
Any more questions or can we close this issue?

**Comment by myluoxz** [comment]
[MM_Big.zip](https://github.com/ConfettiFX/The-Forge/files/3011322/MM_Big.zip)
AssetPipelineCmd  ， If you import this model, what are the steps and specifications?

**Comment by myluoxz** [comment]
[JL.zip](https://github.com/ConfettiFX/The-Forge/files/3021630/JL.zip)

AssimpPipeline Create Runtime Animation There seems to be some problems

**Comment by timoconffx** [comment]
The AssetPipeline requires you to seperate your bind pose mesh with skeleton and the animations into seperate files. For example:
Examples_3/Unit_Tests/UnitTestResources/Animation/fbx/simpleTest contains riggedMesh.fbx. This FBX file contains only the mesh and the skeleton in bind pose.
Examples_3/Unit_Tests/UnitTestResources/Animation/fbx/simpleTest/animations contains two files. Each only contains an animated skeleton. No triangle data is stored in this file.

Our animation middleware has the same requirement. It expects the bind pose and animation seperetly.

If seperating the model from the animation doesn't fix your issue, please send us the code and the assets in FBX format so we can evaluate the problem.

**Comment by myluoxz** [comment]
[riggedMesh.zip](https://github.com/ConfettiFX/The-Forge/files/3037875/riggedMesh.zip)

**Comment by timoconffx** [comment]
Please create two fbx files. One containing only the mesh and the skeleton in bindpose and one with only the animation. Look at the assets in the Examples_3/Unit_Tests/UnitTestResources/Animation/fbx/simpleTest directory if you need an example.

**Comment by myluoxz** [comment]
Hello,  @timoconffx 
I am doing this.  One containing only the mesh and the skeleton in bindpose and one with only the animation. 

Exported with maya,  Validate raw animation failure.
Exported with max,  There will be such an error. As shown above.

why? 

One containing only the mesh and the skeleton in bindpose and one with only the animation. 

Same FBX，  What's the difference?

**Comment by timoconffx** [comment]
@myluoxz 
The zip file you send us contains only one fbx file. This FBX contains both the mesh and the animation. They should be in seperate files. We can't help you if we don't have the files.

FBX files are tricky. There are often problems when importing FBX files, just because all exporters seem to export them differently. A mesh exporter from Blender might work fine. That same mesh exported from Maya might not. We primarily use Blender. You could try exporting the mesh using Blender instead.

**Comment by myluoxz** [comment]
[LuoxzTest.zip](https://github.com/ConfettiFX/The-Forge/files/3053915/LuoxzTest.zip)

**Comment by myluoxz** [comment]
[LuoxzTest-3dsMax.zip](https://github.com/ConfettiFX/The-Forge/files/3053931/LuoxzTest-3dsMax.zip)

**Comment by timoconffx** [comment]
@myluoxz 
You can fix the problem by freezing/applying the transform of your meshes before exporting.

The body and hair mesh both reference "Bip01 Head" and a couple of other bones. The bone offset matrices are stored in mesh local space. Because your meshes are split the bone offset matrix of "Bip01 Head" is different for the body than it is for the hair. Currently the last bone offset that is written to the boneOffsetMatrices vector is taken even if a matrix has already been assigned. Because of this the body was using the bone offset matrix of the hair. This is what is causing the stretching. The problem can be fixed by freezing/applying the transform of your meshes before exporting. Effectively making them use the same local space.

Thank you for helping us figure out this problem. We will try to include a more permanent fix for this problem in our next release.

**Comment by myluoxz** [comment]
![image](https://user-images.githubusercontent.com/17875098/55953546-f5c5c080-5c8e-11e9-8d50-394ba888d4f1.png)
![NewAnim2](https://user-images.githubusercontent.com/17875098/55953569-05450980-5c8f-11e9-8028-47a7693d3b4e.gif)
![NewAnim3](https://user-images.githubusercontent.com/17875098/55953576-09712700-5c8f-11e9-9e9d-57e024ff99a0.gif)

thank you very much， @timoconffx


Solve the problem by freezing/applying the transformation of the grid before exporting.

Is this step done in blender? Still doing it in 3DS Max?
I am not familiar with Blender, ask, in which menu to set the freeze and apply grid transformation, please give a detailed step?

**Comment by timoconffx** [comment]
@myluoxz 
In the next release of the Forge your issue has been fixed.

For now here are the steps to freeze the transform in Blender:
1. Open RiggedMesh.fbx in Blender.
2. Right click the body mesh to select it.
3. Press Ctrl+A while your cursor is over the viewport to open the apply menu.
4. Select Location.
5. Press Ctrl+A again.
6. Select Rotation & Scale.
7. Right click in the hair mesh to select it.
8. Repeat steps 3 to 6.

**Comment by myluoxz** [comment]
@timoconffx
Thank you very much, it has been perfect for it to work, I look forward to the next version, thank you!!

**Comment by wolfgangfengel** [comment]
This should be fixed. Please let us know.

**Comment by wolfgangfengel** [comment]
@myluoxz can you confirm it works for you? In that case, I would close this issue.
