### ISSUE TITLE
DescriptorBinder best practice

### ISSUE THREAD

**Issue by jdswebb** [ConfettiFX/The-Forge#111]
Hi,

I'm trying to use TF in a game editor and I'm a bit confused about how best to use DescriptorBinders in the case where the upper bound on the number of batch/draw updates is unknowable at load time. It is not knowable since the user is free to create new materials and new instances of objects that use them at will.

Currently I have two ideas:

- Start with a low value and destroy/recreate DescriptorBinders on demand
- Start with a value that's potentially orders of magnitude higher than necessary and hope for the best

Neither seems like a great solution, and without being familiar with TFs internals I'm not sure the what the consequences would be. Is there a better way to work around this problem? Could the old dynamic allocation behaviour be made available for this case if not?

Many thanks

**Comment by JesusGumbauConffx** [comment]
Hi jdswebb ,

The DescriptorBinder approach is a flexible tool that gives you control of every aspect of descriptor memory management. This is particularly useful on low-end or mobile devices. What other middleware tools / engines do regarding this is usually just to allocate a large enough amount of descriptor memory under the hood for this and possibly use it as a ring buffer. 

For a game editor that will run on a PC, I think it should be safe to follow this idea and allocate a big chunk of space, since as you say, the user can create content dynamically.

However, please consider this:

- You don’t really want to allocate descriptor space per material, but per shader (since it is initialised using root signatures). Usually, in a game engine, you have a certain amount of shaders that are reused for different materials, since shaders need to be pre-compiled. I am assuming here that your engine uses a similar approach to Unity for the shader / material concepts. So as long as you don’t create new shaders, you can create as much materials as you want without having to “add” them to the descriptor binder.
- As for the amount of instances of objects, since this is not a game where an upper bound could be calculated at load time, I think you could safely follow the old-style approach and just allocate a big chunk of memory for it.
- Please notice that there is a third approach to those you mentioned that could be combined with my last paragraph: create new descriptor binders on demand. You don’t need to destroy the old ones and recreate the new ones. You can keep the old ones and just add new descriptor binders to make room for the new shaders / rendering usage you need to do. You could keep a dictionary that gives you the appropriate descriptor binder to use depending on the rendering usage. 

Hope this helps.

**Comment by jdswebb** [comment]
Many thanks for the reply. I did use 'material' meaning 'shader program' sorry - it's a bad habit I picked up from an another engine I worked with!

I think based on your feedback here I will go with the option of just allocating a large chunk of memory, and if that turns out to be insufficient for any reason, go with your next suggestion of allocating new binders on demand rather than resizing.
