### ISSUE TITLE
Add RenderGraph/FrameGraph support

### ISSUE THREAD

**Issue by cylof22** [ConfettiFX/The-Forge#171]
Is there plan to add RenderGraph/FrameGraph support? It is a modern data-driven rendering architecture?

**Comment by wolfgangfengel** [comment]
Yes, but the render graph would go into separate GitHub repository. This way you can still use The Forge by itself and then there is optional a render graph in a separate directory. This will be what I call an intermediate layer that will be specific to open-world games.

**Comment by cylof22** [comment]
@wolfgangfengel Is it still open-source, or commercial middleware?

**Comment by wolfgangfengel** [comment]
It would be open-source.

**Comment by marfmotz** [comment]
> Is there plan to add RenderGraph/FrameGraph support? It is a modern data-driven rendering architecture?

Render Graph has nothing to do with data-driven, it's a fully code-driven framework

**Comment by raptoravis** [comment]
is there any progress with the rendergraph?

**Comment by wolfgangfengel** [comment]
Coming back to this. We re-prioritized the render graph a bit because it is not as useful anymore in a modern rendering framework. It was a good idea 10+ years ago. With a GPU-driven renderer, you do not make many draw calls. I believe our Visibility Buffer implementation does five ExecuteIndirect calls. Future renderers are probably less. You don't need a render graph to deal with five draw calls ...

**Comment by wolfgangfengel** [comment]
I should have said Dispatch and Draw calls ...
