### ISSUE TITLE
unclear build instructions for Android

### ISSUE THREAD

**Issue by mgood7123** [ConfettiFX/The-Forge#205]
i am currently using Android Studio and CMake, and i am not sure how to go about building an application using The Forge

**Comment by wolfgangfengel** [comment]
There is a section on the homepage of TF that says "Android Requirements". This is what you need to run the Android run-time. Please note the phones we are currently testing on. We currently support Visual Studio 2019. The reason why this is not 2017 is that there is a bug in 2017 that prevents us from using it, otherwise, it would be 2017 similar to many other platforms.

**Comment by mgood7123** [comment]
> There is a section on the homepage of TF that says "Android Requirements". This is what you need to run the Android run-time. Please note the phones we are currently testing on. We currently support Visual Studio 2019. The reason why this is not 2017 is that there is a bug in 2017 that prevents us from using it, otherwise, it would be 2017 similar to many other platforms.

hmm ok, so

i would clone the repo, and then open it directly in Visual Studio 2019?
