### ISSUE TITLE
Visibility Buffer on MacBookPro13,1 not rendered correctly 

### ISSUE THREAD

**Issue by grakkpl** [ConfettiFX/The-Forge#28]
VisibilityBuffer example is not rendered correctly on MacBook Pro 13,1 on 10.13.2 (17C88) - Intel SKL graphics.

Changing the parameters does not change much (or makes it even worse). Any clues?

https://imgur.com/mtNkRo1

**Comment by wolfgangfengel** [comment]
In the moment we do not test Intel-GPU based devices like MacBook Pro's ... but we let Intel and Apple know about the challenges of supporting Intel-based GPUs and I am hoping they see this message :-) The challenges are driver support for some of the features we use in the Visibility Buffer.
Expect this to be fixed at some point. I can't give you an ETA ... but we are actively working on it. Let's keep this issue up here as a reminder.

**Comment by grakkpl** [comment]
I'm sure they will, thanks :)

**Comment by madwax** [comment]
Hi just got the same problem on a MacBook Pro 15 (early 13) running 10.13.2.  I still get the problem however if I switch from using the default device (Intel) to using my Geforce (changing code around MetalRenderer.mm: 850).

I had a look at the 3 errors that get reported to the console.
Fixed (with no change) the metal compiler warning about signed/unsigned 
Fixed (with no change) the problem with ImageFormat::GetBytesPerChannel()  - the assert
I have no idea if  "Execution of the command buffer was aborted due to an error during execution. Invalid Resource (IOAF code 9)" might have an effect.

**Comment by wolfgangfengel** [comment]
That should be solved with today's commit.
