### ISSUE TITLE
heartbeat?

### ISSUE THREAD

**Issue by zazahunter** [ConfettiFX/The-Forge#282]
we havent see anything being done for the last 10 months....

**Comment by Trider12** [comment]
A new version is planned to be released very soon.

**Comment by Trider12** [comment]
I can't give you an exact date. There are still some minor bugs left that need fixing. The release will happen once they are fixed.

**Comment by oscarbg** [comment]
can tease some expected changes?

**Comment by wolfgangfengel** [comment]
We have been testing since March the new release (or was it February?). We changed a ton of code based on all the projects that are using this now. We still waiting for one unit test to finish ... it will cover a cross-platform software rasterizer.

If you had asked me during the time since February when we are going to release my response would have been ... probably in the next 2 - 4 weeks ... so this is also my response today. 
Generally, we work on currently 10 customer projects with The Forge. The good thing is we can integrate a lot of changes learned from that experience. The bad thing is, that our customer projects have priority. This is why the release cycle gets a bit longer ... also the big amount of changes needs more manual testing. Our hardware testing of all platforms is not enough.

**Comment by metaleap** [comment]
@wolfgangfengel The good thing is we can integrate a lot of changes learned from that experience. The bad thing is, that our customer projects have priority.

Here's something to **really** (re?)consider: if you push out WIP stuff early in the repo (or much more often), no matter how patchy or flaky, you'll get plenty more problems-surfaced that "10 customer projects" might just not-_yet_ show, plus perhaps even fixes/patches/PRs for them...

> It's been a long time

Last commit 26 months ago indeed! I mean let's not even talk about "releases" here, but in this space (foss, linuxable 3D realtime) plenty devs are happy to get their hands dirty (and at times even your fixes prepped) from the raw codebase..

**Comment by manas-kulkarni** [comment]
Fixed with the latest release. We plan to release more frequently from here on
