### ISSUE TITLE
Sample Project

### ISSUE THREAD

**Issue by VinnyVicious** [ConfettiFX/The-Forge#288]
I believe it would be beneficiel to have some sort of sample project that pieces The Forge together in a recommended way/best practice. The project could be something simple, like walking around the https://www.intel.com/content/www/us/en/developer/topic-technology/graphics-research/samples.html Sponza scene, with shadows, AO, etc.

**Comment by VinnyVicious** [comment]
This seems to be going in the right direction, although no updates in 2 years: https://github.com/cboiangiu/the-forge-starter

**Comment by wutipong** [comment]
There are quite a few demo projects.

If I'm not mistaken (which is quite likely to), The-Forge is designed to be brought into existing project, rather than to bring the project into The-Forge. Meaning it does not have a set project structure, rather you pick bits and pieces and put it into your project. 

There are quite a lot of people who create templates for it though (even myself have one). You can choose any one you like. Just keep in mind though that the project will mostlikely break if a new version of The-Forge is released and you replace the existing one with that. It's better to stick with one version unless you need to replace IMHO.

Oh and you will get faster response if you ask your questions in the Discord rather than Github. I think they only use github to drop code.

**Comment by VinnyVicious** [comment]
> There are quite a few demo projects.

Would you mind sharing those in this thread so other people can find them?

> If I'm not mistaken (which is quite likely to), The-Forge is designed to be brought into existing project, rather than to bring the project into The-Forge. Meaning it does not have a set project structure, rather you pick bits and pieces and put it into your project.

Absolutely, The-Forge feels like a traditional enterprise framework or middleware. However, most of these have a KitchenSink demo or some sort of Standard project that can be used to show users "this is how we integrate this", and "this is how we recommend to manage that".

**Comment by wutipong** [comment]
> Would you mind sharing those in this thread so other people can find them?

https://github.com/ConfettiFX/The-Forge/tree/master/Examples_3

Under the folder "Unit_Tests", there are several projects and even Visual Studio solution files. I think the rest are demoing integration with some of their products. Worth checking out too.

If you're expecting a fully playable, complex game, as an example project then I think you'd be disappointing. However those example projects should give you everything you need to start a project.

Personally I have The Forge cloned under my git project as a subproject, then I cherry pick some of the files I want and put the list in the CMakeList I use along with my project files. I even have some custom target to handle dll file copy tasks, etc.

However I think there are people who would have a separate CMakeList to handle the forge source/project files, and refer to it using include or as a separate library. 

You could also just cherry pick some of the file and add it in the visual studio solution file of your existing project as well. 

Oh and I think there are someone creates CMake file as well. Though I haven't tried any of these.
